### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MDSharma** [sreeramkannan/Shannon#27]
Hi,

Any thoughts on these two errors that seem to come up with a test data set that I was trying with shannon?
```
cat: /nobackup/beegfs/home/Clean/shannon/Kauto/Kauto_algo_input/rc_2.fasta_74: No such file or directory
rm: cannot remove ‘/nobackup/beegfs/home/Clean/shannon/Kauto/Kauto_algo_input/rc_2.fasta_*’: No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported format
Failed to open input file '/nobackup/beegfs/home/Clean/shannon/Kauto/Kauto_algo_input/jellyfish_p1_output.jf'
282551494
39
Processed No of reads:282551494, Avg. Read length: 39
Fri Mar 29 20:29:15 2019: Starting Jellyfish to extract Kmers from Reads..
Fri Mar 29 20:29:15 2019: Jellyfish finished..
nJobs:70
reads_files:/nobackup/beegfs/home/Clean/shannon/Kauto/Kauto_algo_input/reads_1.fasta /nobackup/beegfs/home/Clean/shannon/Kauto/Kauto_algo_input/reads_2.fasta
Fri Mar 29 20:29:15 2019: Starting Kmer error correction..
Traceback (most recent call last):
  File "/cm/shared/admin-apps/shannon/0.0.2/bin/shannon.py", line 460, in <module>
    k1mer_dictionary,reads = extension_correction(str_ec.split(),dontWriteToFile)
  File "/cm/shared/admin-apps/shannon/0.0.2/bin/extension_correction.py", line 546, in extension_correction
    allowed_kmer_dict, reads = run_correction(infile, outfile, min_weight, min_length, double_stranded, comp_directory_name, comp_size_threshold, True, inMem, nJobs, reads_files)
  File "/cm/shared/admin-apps/shannon/0.0.2/bin/extension_correction.py", line 315, in run_correction
    kmers, K = load_kmers(infile, double_stranded,polyA_del)
  File "/cm/shared/admin-apps/shannon/0.0.2/bin/extension_correction.py", line 218, in load_kmers
    K = len(kmers.keys()[0])
IndexError: list index out of range
```

**Comment by olivomao** [comment]
Hi,
We have a newest Shannon developed in C++ and tested in more datasets. Would you try this here: https://github.com/bx3/Shannon_Cpp_RNA_seq/wiki 

The Python version here looks a bit out of date. Thanks!

**Comment by MDSharma** [comment]
Thanks, sounds like a plan... Trying it now.

Best Regards,
MD Sharma(sent via a mobile device.. please blame the AI driven autocorrect algorithm for any errors)

________________________________
