### ISSUE TITLE
shannon: KeyError: '\x1f'

### ISSUE THREAD

**Issue by awata-hiroko** [sreeramkannan/Shannon#29]
Hi

Does anyone solve the below error that came up when I was trying shannon?

```
Thu Oct 10 13:24:20 2019: Starting Shannon run..
Traceback (most recent call last):
  File "/home/***/Shannon/rc_s.py", line 35, in <module>
    main()
  File "/home/***/Shannon/rc_s.py", line 30, in main
    reverse_complement_serial(infile, outfile)
  File "/home/***/Shannon/rc_s.py", line 16, in reverse_complement_serial
    reads.append(reverse_complement(fields[0]))
  File "/home/***/Shannon/rc_s.py", line 3, in <lambda>
    reverse_complement = lambda x: ''.join([D[B] for B in x][::-1])
KeyError: '\x1f'
cat: /datadrive/***/Assemble/Shannon/test_all/test_all_algo_input/rc.fasta: No such file or directory
/bin/rm: cannot remove '/datadrive/Assemble/Shannon/test_all/test_all_algo_input/rc.fasta': No such file or directory
Processed No of reads:3510991, Avg. Read length: 265.984430891
Thu Oct 10 13:24:23 2019: Starting Jellyfish to extract Kmers from Reads..
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported format
Aborted (core dumped)
Failed to open input file '/datadrive/***/Assemble/Shannon/test_all/test_all_algo_input/jellyfish_p1_output.jf'
Thu Oct 10 13:24:24 2019: Jellyfish finished..
nJobs:1
reads_files:/datadrive/***/Assemble/Shannon/test_all/test_all_algo_input/reads.fasta
Thu Oct 10 13:24:24 2019: Starting Kmer error correction..
Traceback (most recent call last):
  File "/home/***/Shannon/shannon.py", line 459, in <module>
    k1mer_dictionary,reads = extension_correction(str_ec.split(),dontWriteToFile)
  File "/home/***/Shannon/extension_correction.py", line 548, in extension_correction
    allowed_kmer_dict, reads = run_correction(infile, outfile, min_weight, min_length, double_stranded, comp_directory_name, comp_size_threshold, True, inMem, nJobs, reads_files)
  File "/home/***/Shannon/extension_correction.py", line 317, in run_correction
    kmers, K = load_kmers(infile, double_stranded,polyA_del)
  File "/home/***/Shannon/extension_correction.py", line 220, in load_kmers
    K = len(kmers.keys()[0])
IndexError: list index out of range
```

**Comment by bx3** [comment]
Can you give a sample of your input? I am guessing it is the input format issue. 

rc.fasta is an intermediate file, which generates a reverse complement of your input reads. For some reason the process crushes at this step(first key error). So then when a python dictionary "kmers" tries to load something, it pops another error since there is no element due to rc.fasta error.

I will suggest to try a newer Shannon implemented in C++, it is at
https://github.com/bx3/Shannon_Cpp_RNA_seq

**Comment by awata-hiroko** [comment]
Thanks for your replying so fast.

I solved it by gunzip my fastq files. 
Sorry, I haven't realized that the file must be not compressed.
