### ISSUE TITLE
can't run shannon outside installation dir

### ISSUE THREAD

**Issue by macmanes** [sreeramkannan/Shannon#3]
run code: (run in another dir, not where shannon is installed)

```
python /share/shannon/shannon.py -k25 -o shannon20Mk25 --left ../rcorr20M/20.subsamp_1.cor.fq --right ../rcorr20M/20.subsamp_2.cor.fq -p 60
```

error:

```
--------------------------------------------
Shannon: RNA Seq de novo Assembly
--------------------------------------------
Checking the various dependencies
--------------------------------------------
Using jellyfish in /share/quorum/bin/jellyfish
Using GPMETIS in /usr/bin/gpmetis
--------------------------------------------
Wed Feb 10 07:12:04 2016: Starting Shannon run..
Using Quorum in /share/quorum/bin/quorum
Using GNU Parallel in /usr/bin/parallel
Wed Feb 10 07:12:04 2016: Running Quorum for read error correction with quality scores..
python: can't open file 'run_quorum.py': [Errno 2] No such file or directory
Wed Feb 10 07:12:04 2016: Starting Jellyfish to extract Kmers from Reads..
terminate called after throwing an instance of 'std::runtime_error'
  what():  Can't open file '/mnt/data3/macmanes/error/shannon/shannon20Mk25/corrected_reads_1.fa'
Aborted (core dumped)
Failed to open input file '/mnt/data3/macmanes/error/shannon/shannon20Mk25/shannon20Mk25_algo_input/jellyfish_p1_output.jf'
Wed Feb 10 07:12:04 2016: Jellyfish finished..
python: can't open file 'extension_correction.py': [Errno 2] No such file or directory
python: can't open file 'kp1mer_to_kmer.py': [Errno 2] No such file or directory
Wed Feb 10 07:12:04 2016: gpmetis for partitioning 1 is complete --
Wed Feb 10 07:12:04 2016: k1mers2component dictionary created
Traceback (most recent call last):
  File "/share/shannon/shannon.py", line 288, in <module>
    [components_broken, new_components] = kmers_for_component(kmer_directory, reads_files, base_directory_name, r1_contig_file_extension, r1_new_kmer_tag, r1_graph_file_extension, get_og_comp_kmers, get_partition_kmers, double_stranded, paired_end, False, partition_size, overload, K, gpmetis_path)
  File "/share/shannon/kmers_for_component.py", line 197, in kmers_for_component
    readfile1 = open(reads_files[0], 'r')
IOError: [Errno 2] No such file or directory: '/mnt/data3/macmanes/error/shannon/shannon20Mk25/corrected_reads_1.fa'
```

other info:
I made the python scripts in /shannon executable after I got this error the 1st time, but no luck. 

```
which run_quorum.py
/share/shannon//run_quorum.py
```

please advise.

**Comment by macmanes** [comment]
fixed:

**Comment by sreeramkannan** [comment]
I have updated Shannon to use a variable called Shannon_dir which is the path where Shannon files are stored. This is automatically configured now from the files.
